trigger:
  branches:
    include:
      - BTCS1_Login_Signup

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/dist'
    ArtifactName: 'cracker-frontend-app1'
  displayName: 'Publish Artifact: drop'

