# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- BTCS1_Login_Signup

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration=production  # Build for production
  displayName: 'Install Angular CLI and Build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/dist'  # Path to Angular build output directory
    artifactName: 'angular-dist'
    publishLocation: 'Container'
  displayName: 'Publish Angular Build Artifacts'

# - - task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students (6ebbb3bc-8b53-4226-bb05-d7851352144a)'
    appType: 'webApp'
    WebAppName: 'DEV-D'
    deployToSlotOrASE: true
    ResourceGroupName: 'cracker-admin-dashboard'
    SlotName: 'production'
    VirtualApplication: 'cracker-frontend'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'